-- Temporarily disable RLS for data import
-- Run this BEFORE importing data, then re-enable after

-- Disable RLS on all tables for import
ALTER TABLE athletes DISABLE ROW LEVEL SECURITY;
ALTER TABLE activities DISABLE ROW LEVEL SECURITY;
ALTER TABLE gear DISABLE ROW LEVEL SECURITY;
ALTER TABLE routes DISABLE ROW LEVEL SECURITY;
ALTER TABLE segments DISABLE ROW LEVEL SECURITY;
ALTER TABLE follows DISABLE ROW LEVEL SECURITY;
ALTER TABLE comments DISABLE ROW LEVEL SECURITY;
ALTER TABLE reactions DISABLE ROW LEVEL SECURITY;
ALTER TABLE memberships DISABLE ROW LEVEL SECURITY;
ALTER TABLE challenge_participations DISABLE ROW LEVEL SECURITY;
ALTER TABLE goals DISABLE ROW LEVEL SECURITY;
ALTER TABLE media DISABLE ROW LEVEL SECURITY;
ALTER TABLE connected_apps DISABLE ROW LEVEL SECURITY;
ALTER TABLE logins DISABLE ROW LEVEL SECURITY;
ALTER TABLE general_preferences DISABLE ROW LEVEL SECURITY;
ALTER TABLE email_preferences DISABLE ROW LEVEL SECURITY;
ALTER TABLE social_settings DISABLE ROW LEVEL SECURITY;
ALTER TABLE visibility_settings DISABLE ROW LEVEL SECURITY;

-- Also disable on any other tables that might have RLS
ALTER TABLE challenges DISABLE ROW LEVEL SECURITY;
ALTER TABLE clubs DISABLE ROW LEVEL SECURITY;

-- Show status
SELECT schemaname, tablename, rowsecurity
FROM pg_tables
WHERE schemaname = 'public'
ORDER BY tablename;